const stops=[

{name:"Guatemala City Historic Center",lat:14.6349,lng:-90.5069,important:"Mission launch point. Historic churches.",interesting:"Capital founded in 1776."},
{name:"Zone 1 Cathedral",lat:14.636,lng:-90.513,important:"Major Catholic landmark.",interesting:"Faces Constitution Plaza."},
{name:"Cayala Area",lat:14.607,lng:-90.485,important:"Safe meeting area.",interesting:"Modern colonial architecture."},
{name:"San Jose Pinula",lat:14.545,lng:-90.411,important:"Growing suburb outreach.",interesting:"Coffee farming region."},
{name:"Palencia",lat:14.664,lng:-90.358,important:"Rural ministry opportunities.",interesting:"Mountain climate."},
{name:"San Antonio La Paz",lat:14.756,lng:-90.284,important:"Community church work.",interesting:"Quiet agricultural town."},
{name:"El Rancho",lat:14.798,lng:-90.320,important:"Highway junction stop.",interesting:"Frequent travel checkpoint."},
{name:"Sanarate",lat:14.796,lng:-90.192,important:"Eastern corridor ministry.",interesting:"Popular roadside markets."},
{name:"Guastatoya Center",lat:14.8537,lng:-90.069,important:"El Progreso capital.",interesting:"Very hot climate."},
{name:"Guastatoya Church Area",lat:14.851,lng:-90.065,important:"Local evangelical activity.",interesting:"Strong youth ministries."},
{name:"Morazan",lat:14.931,lng:-89.918,important:"Rural outreach region.",interesting:"Livestock economy."},
{name:"San Agustin Acasaguastlan",lat:14.936,lng:-89.969,important:"Historic Spanish town.",interesting:"Colonial roots."},
{name:"San Cristobal Acasaguastlan",lat:14.925,lng:-89.869,important:"Village ministry.",interesting:"Ancient indigenous presence."},
{name:"El Jicaro",lat:14.914,lng:-89.741,important:"Small community missions.",interesting:"Dry eastern terrain."},
{name:"Cabanas",lat:14.931,lng:-89.807,important:"Mountain outreach.",interesting:"Traditional rural lifestyle."},
{name:"Usumatlan",lat:14.988,lng:-89.783,important:"Strategic travel stop.",interesting:"Cattle ranching region."},
{name:"Rio Hondo",lat:15.0367,lng:-89.5839,important:"Gateway to Zacapa.",interesting:"One of hottest towns."},
{name:"Rio Hondo Park",lat:15.037,lng:-89.585,important:"Public gathering place.",interesting:"Central community hub."},
{name:"Gualan",lat:15.133,lng:-89.367,important:"Evangelical churches growing.",interesting:"Banana plantations."},
{name:"Gualan Market",lat:15.132,lng:-89.366,important:"Food distribution area.",interesting:"Busy commerce center."},
{name:"La Union Zacapa",lat:14.971,lng:-89.287,important:"Remote mountain ministry.",interesting:"Coffee production."},
{name:"Huite",lat:15.016,lng:-89.707,important:"Village outreach.",interesting:"Traditional Mayan culture."},
{name:"Zacapa Entrance",lat:14.974,lng:-89.531,important:"Mission destination region.",interesting:"Desert-like climate."},
{name:"Zacapa Central Park",lat:14.9722,lng:-89.5333,important:"Community events hub.",interesting:"Land of Eternal Sun."},
{name:"Zacapa Cathedral Area",lat:14.973,lng:-89.534,important:"Local churches.",interesting:"City center activity."},
{name:"Zacapa Bus Terminal",lat:14.97,lng:-89.528,important:"Travel logistics.",interesting:"Major transport hub."},
{name:"Teculutan",lat:14.983,lng:-89.72,important:"Community outreach.",interesting:"Near archaeological zones."},
{name:"Teculutan Church",lat:14.984,lng:-89.721,important:"Local partner church.",interesting:"Strong youth participation."},
{name:"Estanzuela",lat:14.994,lng:-89.567,important:"Small town ministry.",interesting:"Home to fossil museum."},
{name:"Estanzuela Fossil Museum",lat:14.996,lng:-89.566,important:"Educational stop.",interesting:"Prehistoric fossils found."},
{name:"Cabanas Zacapa",lat:14.945,lng:-89.762,important:"Rural evangelism.",interesting:"Dry forest landscapes."},
{name:"San Diego Zacapa",lat:14.932,lng:-89.625,important:"Village church work.",interesting:"Agricultural economy."},
{name:"La Fragua",lat:14.91,lng:-89.61,important:"Community development.",interesting:"Local crafts."},
{name:"San Jorge",lat:14.892,lng:-89.52,important:"Local outreach.",interesting:"Small farming villages."},
{name:"El Terrero",lat:14.889,lng:-89.47,important:"Remote missions.",interesting:"Mountain terrain."},
{name:"Santa Rosita",lat:14.865,lng:-89.45,important:"Rural school ministry.",interesting:"Traditional festivals."},
{name:"Los Achiotes",lat:14.85,lng:-89.44,important:"Village outreach.",interesting:"Local produce markets."},
{name:"San Vicente",lat:14.835,lng:-89.42,important:"Community support.",interesting:"Dry climate farming."},
{name:"San Pablo",lat:14.82,lng:-89.41,important:"Church partnership.",interesting:"Small population."},
{name:"El Amatillo",lat:14.805,lng:-89.4,important:"Food distribution.",interesting:"Border trade influence."},
{name:"Monte Grande",lat:14.79,lng:-89.39,important:"Youth programs.",interesting:"Hillside views."},
{name:"Los Vados",lat:14.775,lng:-89.38,important:"Evangelism outreach.",interesting:"River crossings."},
{name:"El Rosario",lat:14.76,lng:-89.37,important:"Village ministry.",interesting:"Rural farming."},
{name:"San Lorenzo",lat:14.745,lng:-89.36,important:"Community health missions.",interesting:"Local markets."},
{name:"Las Flores",lat:14.73,lng:-89.35,important:"Children ministry.",interesting:"Seasonal agriculture."},
{name:"El Jute",lat:14.715,lng:-89.34,important:"Pastoral visits.",interesting:"Quiet rural life."},
{name:"Los Encuentros",lat:14.70,lng:-89.33,important:"Meeting location.",interesting:"Highway crossroads."},
{name:"La Reforma",lat:14.685,lng:-89.32,important:"Village church support.",interesting:"Small farming community."},
{name:"Nueva Esperanza",lat:14.67,lng:-89.31,important:"New church plant.",interesting:"Name means New Hope."},
{name:"El Paraiso",lat:14.655,lng:-89.30,important:"Final outreach area.",interesting:"Warm lowland region."}

];
